# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-20 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20170817_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_content',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
