# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-20 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20170820_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
